### ISSUE TITLE
加入申请

### ISSUE THREAD

**Issue by RiermanniyaLiYu** [agorahub/_join#22]
Hello：

我是在搜索“躺平”一词时，偶尔看到Agora的，被平台上诸多有见地的文章所打动，细细阅读几篇后，大大地缓解了我严重的政治性抑郁，看到可以加入，我马上就点了进来，希望可以加入Agora，遇到更多三观合拍的朋友，同时也希望为平台贡献一些力量。

盼复！

PS：个人的邮箱是liyu9713@gmail.com

**Comment by theagora** [comment]
existing member.
